### PR TITLE
Make it easier to install YottaDB from a source or binary tarball

### PR DESCRIPTION
**Pull request by nars1**
README.md : Make it easier to build and install YottaDB from source

ydbinstall.sh
  a) Fix more occurrences of GT.M/gtm to YottaDB/ydb
  b) Make help more useful by printing some example usages
  c) Do not print full help in case of an error. Just point to help so actual error is highlighted.
  d) Add support for Linux on ARMV7L
  e) Fix bug (default case label should be "*" and not "default")
  f) Derive YottaDB release # (not GT.M version #) if ydbinstall and mumps are bundled together
  g) Issue error messages if wget fails
  h) Starting YottaDB r1.10, there will be binary tarballs for Linux x86_64, RHEL x86_64
     and Linux armv7l (named yottadb_r110_linux_x8664_pro.tgz, yottadb_r110_rhel7_x8664_pro.tgz
     and yottadb_r110_linux_armv7l_pro.tgz respectively). Enhance this script to determine the
     appropriate tarball for the current host and download it.

### CODE REVIEW

**Comment by shabiel** [comment]
Narayanan,

I will take a look at it tomorrow.

--Sam

**Comment by nars1** [comment]
Thanks Sam. That is fine.

**Comment by shabiel** [comment]
Nars,

I compiled the source and ./configure installs properly on Centos 7. I just
tested on an existing vista db.

ydbinstall.sh is supposed to be silent. It isn't. Says the following:

If RemoveIPC=yes is configured for systemd, ipcs (database shm & sem) are
removed for a non-system user's processes when that user logs out.
That can cause database operations to fail with mysterious errors.
The installation would like to add the below two lines to
/etc/systemd/logind.conf
   # YottaDB/GT.M : Override systemd default of RemoveIPC=yes to prevent
automatic ipc removal of Shared Memory Segments and Semaphore Arrays of
orphaned databases
   RemoveIPC=no
And issue the below command to restart systemd-logind
   systemctl restart systemd-logind
Do you wish to proceed (Y/N)?

It shouldn't ask. It should just do it.

FYI: The install on Centos requires the following:
git, cmake, tcsh, libconfig-devel, gpgme-devel, libicu-devel,
libgpg-error-devel, libgcrypt-devel, ncurses-devel, openssl-devel,
zlib-devel, gcc, elfutils-libelf-devel.

--Sam

**Comment by shabiel** [comment]
Also, there is an architectural problem: configure should contain all the
interactive portions; gtminstall should take menu options and drive
configure.

**Comment by nars1** [comment]
Sam, this is a one-time setup thing new to GT.M V63002. That said, I will take care of avoiding the RemoveIPC question in ydbinstall. I did not understand your comment about the architectural problem. configure is the one that contains all the interactive portions currently. Did you find any interactive portion in ydbinstall? The RemoveIPC part you noticed was also in configure (not ydbinstall).

**Comment by nars1** [comment]
Sorry I do see the RemoveIPC part is in ydbinstall and not configure. I will see if that can be moved.

**Comment by shabiel** [comment]
Narayanan,

I just found this error message:

%GTM-E-VERMISMATCH, Attempt to access /var/db/vxvista15.0/g/mumps.dat with
version YottaDB r1.10 Linux x86_64, while already using GT.M V6.3-002 Linux
x86_64
%GTM-E-VERMISMATCH, Attempt to access /var/db/vxvista15.0/g/tempgbl.dat
with version YottaDB r1.10 Linux x86_64, while already using GT.M V6.3-002
Linux x86_64

I don't have any processes running right now--how can I fix this error?

--Sam

**Comment by nars1** [comment]
Sam, you can run a "mupip rundown -file <full-path-of-mumps.dat>" using GT.M V6.3-002 and that should remove the database shared memory which would then enable YottaDB r1.10 to create a new shared memory and open the database file.

**Comment by shabiel** [comment]
I should have said: I tried that and I even restarted the computer; and the
problem happened again. It seems to happen when I access YottaDB via GTMCI
and via mumps -run/mumps -dir. I switch back to the YottaDB version I
compiled two weeks ago and everything was fine there.

**Comment by nars1** [comment]
YottaDB used to allow coexisting with GT.M previously. It no longer does that (safeguard since the two versions could have a different shared memory layout). That is probably why you did not see it before but see it now. The issue of mixing GT.M and YottaDB versions in the same database was most likely there even before.

Where is gtm_dist env var pointing to when you run this particular test case? GT.M V63002 or YottaDB r1.10?

Can you describe the set of steps you do a bit more? I am not able to construct a scenario here from your description. Thanks.

**Comment by shabiel** [comment]
$gtm_dist pointed to YottaDB r1.10. GT.M IS NOT INSTALLED on that machine.

I am not totally clear on how it happened either. If it may help you, I can
compile YottaDB in debug mode and get a stack trace somehow.

My guess is that GTMCI still thinks it's using GT.M version number.

--Sam

**Comment by nars1** [comment]
GTMCI should use whatever gtm_dist env var points to. So still not sure how that can point to V63002 when that version is not installed on that box. A few questions.

1) What command gives you the VERMISMATCH error? Is it a MUMPS or MUPIP invocation? If MUPIP, is it a MUPIP RUNDOWN?
2) Which git commit of the source tree does this local build of your YottaDB r1.10 correspond to?

**Comment by nars1** [comment]
Sam, thanks for the review. I have addressed all your comments and pushed a few more commits. Please review them.

**Comment by shabiel** [comment]
There is a stylistic issue--I don't really care; but you may want to ask
Bhaskar.

Typically, gtminstall (and its successor) create a string to answer the
questions. You set an environment variable to answer the systemd question.
That works fine, but I wanted to know if others are okay with it.

I will try the ydbinstall tomorrow (by itself; and then with YottaDB source
drop; and then the ./configure script) and make sure everything is working.
One problem which we may have to wait to fix is that the standalone
ydbinstall calls a git api--I wrote that code, but I don't know whether it
will work when there are multiple releases for YottaDB. It works now since
there is just one release. It *should* work, but I can never tell until we
have a new release.

--Sam

**Comment by nars1** [comment]
Sure. Will check with Bhaskar on the stylistic issue.
Regarding the git api, I did make changes to it to handle multiple releases and pick the right one for the platform of interest. These changes were part of the original pull request commit.

**Comment by shabiel** [comment]
Okay. I just tried the different combinations.

I found a bug in the code, which was already existing (line 444):

      #if [ $platform = "linux" ] ; then
      # # If the current host is a RHEL box then set the OS to RHEL (not
Linux) as there is a RHEL-specific tarball.
      # # We check that it is a RHEL box by the existence of the file
/etc/redhat-release
      # if [ -e /etc/redhat-release ] ; then
      #   platform="rhel"
      # fi
      #fi


I only see this because I am running my tests on CentOS--as far as I
remember, I never saw rhel-specific releases for GT.M ever. This part of
the code causes the downloader to fail.

The other comment I have is that the configure script uses the user and
group bin/bin by default. I am a young thing, and I don't ever remember
coming across a default user of bin/bin. Can we just change it to root/root?

--Sam

**Comment by nars1** [comment]
The RHEL specific code is new as part of this pull request. We will have a rhel-specific tarball starting r1.10. That code is under YottaDB-release-specific code. So it should not apply in case you chose a GT.M version install. That said, did you actually find the ydbinstall script do the wrong thing?

Coincidentally, the configure script has already been changed to use root/root as part of a separate change that is already committed. :)

**Comment by shabiel** [comment]
Oh I see! I was testing it in standalone mode--There is currently no RHEL
release on github; so I got nothing to download, and the script failed.

Good on the configure thing!

**Comment by nars1** [comment]
I now realize it is an issue with downloading r1.00 on RHEL. Will fix it. Thanks.

**Comment by nars1** [comment]
All your comments are now addressed. I have included a --donotchangeRemoveIPC option and fixed the RHEL/CentOS download issue with r1.00.

**Comment by shabiel** [comment]
Looks good!

**Comment by nars1** [comment]
Thanks for the review. I will merge this into the main repo.

**Pull request closed without merging**
